*** Settings ***
Documentation    Automated Test Suite — Infotainment Media & Bluetooth
...              Generated by AutoTest AI (GPT-4 + NLP Pipeline)
...              Requirement Source: IVI_MEDIA_REQ_v2.3.docx
...              Generated On: 2025-03-31T09:00:00Z
...              Traceability ID: REQ-245963, REQ-245964, REQ-245965

Resource         ${TAF_PATH}/import.resource
Resource         ${TAF_PATH}/project/test/keywords/components/media.resource
Resource         ${TAF_PATH}/project/test/keywords/components/bluetooth.resource
Resource         ${TAF_PATH}/project/test/keywords/components/hmi.resource
Resource         ${TAF_PATH}/project/test/keywords/components/phone.resource

Suite Setup      Initialize IVI System And Verify Ready State
Suite Teardown   Collect All Logs And Shutdown IVI
Test Setup       Reset IVI To Default State
Test Teardown    Run Keywords
...              Capture Screenshot On Failure    AND
...              Log Current System State

*** Variables ***
${IVI_URL}              http://192.168.1.100:8080
${TIMEOUT}              30s
${MEDIA_TIMEOUT}        10s
${BT_TIMEOUT}           15s
${SKIP_WAIT}            3s
${USB_MOUNT_PATH}       /media/usb0
${SCREENSHOT_DIR}       ${OUTPUT_DIR}/screenshots
${LOG_DIR}              ${OUTPUT_DIR}/logs

*** Test Cases ***

# ═══════════════════════════════════════════════════════════════
# REQUIREMENT: REQ-245963
# TITLE: Media Playback — Unsupported File Handling
# PRIORITY: High | TYPE: Positive + Negative
# ═══════════════════════════════════════════════════════════════

Testcase_245963_POS: Media Playback Unsupported Files — System Skips After 3s
    [Documentation]    System waits 3 seconds then automatically skips unsupported file
    ...                REQ-245963 | Positive | Priority: High
    [Tags]             media    usb    positive    regression    REQ-245963
    [Setup]            Mount USB With Mixed Files    supported=5    unsupported=3

    prj.test.components.hmi.navigation bar.media.sources : USB
    prj.test.components.media: Launch Source USB
    prj.test.components.media: Open browse in media
    prj.test.components.media: Open Folder from media
    prj.test.components.media: Navigate To Unsupported File    extension=.flac
    prj.test.components.media: Play Song from browser

    # Verify system waits exactly 3 seconds before skip
    ${start_time}=    Get Time    epoch
    Wait Until Keyword Succeeds    5s    500ms
    ...    Verify Skip In Progress

    ${elapsed}=    Calculate Elapsed Seconds    ${start_time}
    Should Be True    2.5 <= ${elapsed} <= 3.5
    ...    msg=Skip should occur at 3s, actual: ${elapsed}s

    prj.test.components.media: Press Previous after 3s
    Verify Current Track    index=previous
    Verify Playback State    PLAYING
    Capture Screenshot    TC_245963_POS_PASS

Testcase_245963_NEG: Media Playback — Corrupted Unsupported File Handling
    [Documentation]    System handles corrupted unsupported file gracefully without crash
    ...                REQ-245963 | Negative | Priority: High
    [Tags]             media    usb    negative    regression    REQ-245963

    prj.test.components.hmi.navigation bar.media.sources : USB
    prj.test.components.media: Launch Source USB
    prj.test.components.media: Open browse in media
    prj.test.components.media: Open Folder from media
    prj.test.components.media: Navigate To Corrupted File
    prj.test.components.media: Attempt Play Corrupted File

    Verify Error Message Displayed    expected=File format not supported
    Verify System State               expected=IDLE
    Verify No System Crash
    Capture Screenshot    TC_245963_NEG_PASS

Testcase_245963_EDGE: Media Playback — Skip At Exactly 3.0 Second Boundary
    [Documentation]    Boundary condition: file skipped at exactly T=3.0s
    ...                REQ-245963 | Edge Case | Priority: Medium
    [Tags]             media    usb    edge    boundary    REQ-245963

    prj.test.components.hmi.navigation bar.media.sources : USB
    prj.test.components.media: Launch Source USB
    prj.test.components.media: Play Timed Unsupported File    inject_at_seconds=3.0

    ${skip_time}=    Measure Skip Event Time
    Should Be True    ${skip_time} >= 3.0    msg=Must wait full 3s before skip
    Should Be True    ${skip_time} <= 3.2    msg=Skip should not exceed 3.2s

# ═══════════════════════════════════════════════════════════════
# REQUIREMENT: REQ-245964
# TITLE: Bluetooth Audio — Device Pairing and Connection
# ═══════════════════════════════════════════════════════════════

Testcase_245964_POS: Bluetooth Device Pairing — PIN Confirmation Flow
    [Documentation]    BT device pairs successfully with 4-digit PIN confirmation
    ...                REQ-245964 | Positive | Priority: High
    [Tags]             bluetooth    pairing    positive    smoke    REQ-245964

    prj.test.components.hmi.navigation bar.connectivity : Bluetooth
    prj.test.components.bluetooth: Enable Bluetooth Discovery
    prj.test.components.bluetooth: Wait For Device In List    ${BT_TEST_DEVICE}    timeout=${BT_TIMEOUT}
    prj.test.components.bluetooth: Select Device For Pairing    ${BT_TEST_DEVICE}

    ${pin}=    prj.test.components.bluetooth: Get Displayed PIN
    Should Match Regexp    ${pin}    ^[0-9]{4}$    msg=PIN must be 4 numeric digits, got: ${pin}

    prj.test.components.phone: Confirm Pairing PIN    ${pin}
    prj.test.components.bluetooth: Verify Connection Status    CONNECTED
    Capture Screenshot    TC_245964_POS_PASS

Testcase_245964_NEG: Bluetooth — Wrong PIN Rejection
    [Documentation]    System rejects pairing when incorrect PIN entered
    ...                REQ-245964 | Negative | Priority: High
    [Tags]             bluetooth    pairing    negative    REQ-245964

    prj.test.components.hmi.navigation bar.connectivity : Bluetooth
    prj.test.components.bluetooth: Enable Bluetooth Discovery
    prj.test.components.bluetooth: Select Device For Pairing    ${BT_TEST_DEVICE}
    prj.test.components.phone: Enter Wrong PIN    0000

    Verify Pairing Failed Message    expected=Incorrect PIN
    Verify Connection Status         expected=DISCONNECTED
    Capture Screenshot    TC_245964_NEG_PASS

# ═══════════════════════════════════════════════════════════════
# REQUIREMENT: REQ-245965
# TITLE: Navigation — GPS Fix Acquisition
# ═══════════════════════════════════════════════════════════════

Testcase_245965_POS: GPS Fix Acquired Within 30 Seconds — Open Sky
    [Documentation]    GPS fix acquired within 30s in open sky conditions
    ...                REQ-245965 | Positive | Priority: High
    [Tags]             navigation    gps    positive    performance    REQ-245965

    prj.test.components.hmi.navigation bar.nav : Navigation
    prj.test.components.hmi: Launch Navigation App
    ${start}=    Get Time    epoch

    Wait Until GPS Fixed    timeout=30s
    ${elapsed}=    Calculate Elapsed Seconds    ${start}

    Should Be True    ${elapsed} <= 30    msg=GPS fix took ${elapsed}s, max 30s
    Verify GPS Signal Strength    minimum=3
    Capture Screenshot    TC_245965_POS_PASS

*** Keywords ***

Initialize IVI System And Verify Ready State
    [Documentation]    Full system boot sequence with readiness check
    Log    Initializing IVI System...    console=True
    Connect To IVI    host=${IVI_URL}
    Wait Until IVI Ready    timeout=60s
    Verify All Services Running
    Set Screenshot Directory    ${SCREENSHOT_DIR}
    Log    IVI System Ready    console=True

Collect All Logs And Shutdown IVI
    Collect System Logs    destination=${LOG_DIR}
    Generate Test Report
    Disconnect From IVI

Reset IVI To Default State
    Clear Media Queue
    Disable All Active Connections
    Navigate To Home Screen
    Sleep    1s

Capture Screenshot On Failure
    Run Keyword If Test Failed
    ...    Capture Page Screenshot
    ...    ${SCREENSHOT_DIR}/FAIL_${TEST NAME}_${SUITE NAME}.png

Calculate Elapsed Seconds
    [Arguments]    ${start_epoch}
    ${now}=    Get Time    epoch
    ${elapsed}=    Evaluate    ${now} - ${start_epoch}
    RETURN    ${elapsed}
